language: php

php:
  - 7.3
  - 7.4
  - 8.0

install:
  - composer install --prefer-dist --no-interaction --no-suggest

before_script:
  - if [ $TRAVIS_PHP_VERSION = "8.0" ]; then pecl install pcov; fi

script:
  - vendor/bin/phpstan analyse
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
